"""add sales tax field

Revision ID: 0e986ef61028
Revises: 2ae16ae23d0e
Create Date: 2025-12-06 09:40:18.749385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e986ef61028'
down_revision: Union[str, None] = '2ae16ae23d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sales_tax', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'sales_tax')
    # ### end Alembic commands ###
